### ISSUE TITLE
Description should be either text or html

### ISSUE THREAD

**Issue by aexol** [graphql-editor/diagram#154]
Add option in configuration for text or html description. Right now it is only html but should be also available in innerText mode

**Comment by aexol** [comment]
We should move to the plain text description instead of contentEditable html

**Comment by aexol** [comment]
![description_plain_text](https://user-images.githubusercontent.com/779748/77210123-78dad200-6b00-11ea-95cb-c573109fb7b1.gif)

**Comment by kachakot** [comment]
https://github.com/graphql-editor/diagram/pull/174
