### ISSUE TITLE
Jumping of diagram pan

### ISSUE THREAD

**Issue by aexol** [graphql-editor/diagram#169]
Sometimes with many clicks diagram pan jumps. Video attached:

![wrongpostionofmouseevent 2020-03-20 14_56_40](https://user-images.githubusercontent.com/779748/77170231-0562a180-6abb-11ea-8eaa-64bccf1b4a12.gif)

**Comment by kachakot** [comment]
@aexol what browser does this problem appear on? I can't generate this issue:
https://www.loom.com/share/97a74c6f109e4a6d84fc262ac5d72cc3
Tested on Chrome, Safari, Firefox

**Comment by hzub** [comment]
Possibly fixed by https://github.com/graphql-editor/diagram/pull/175
