### ISSUE TITLE
Add text filter over the nodes list

### ISSUE THREAD

**Issue by aexol** [graphql-editor/diagram#182]
![Screenshot 2020-04-30 at 15 49 39](https://user-images.githubusercontent.com/779748/80718335-4e663680-8afa-11ea-994e-ab509f47d53c.png)
When you open the menu it should be possible to type to filter the displayed types in the menu. Sometimes you have 200 types and filtering would be useful. 

Input should appear in the top of the menu and should be discussed with UX

**Comment by Zedzian** [comment]
I will take a look into it

**Comment by Zedzian** [comment]
@aexol, does this ticket relate to diagram project or rather graphql-editor?

**Comment by hzub** [comment]
Menu system is part of diagram's implementation, take a look at `src/Diagram/stateManager/menuManager/index.ts` mechanism

**Comment by Zedzian** [comment]
@hzub thanks :)
