### ISSUE TITLE
Only vertical segment of link is interactive

### ISSUE THREAD

**Issue by smeijer** [graphql-editor/diagram#74]
Only the vertical segment of the link is interactive. Besides the fact that it's visually not 100% correct when hovering. It has also some usability issues for link removal.

The link context menu, can only be accessed when clicking the vertical segment of the link:

![graphsource](https://user-images.githubusercontent.com/1196524/53498649-00dddc00-3aa7-11e9-9c15-9b387379878d.gif)

**Comment by aexol** [comment]
I can add 2 more trees for these segments
