### ISSUE TITLE
Link should have directional indicator

### ISSUE THREAD

**Issue by smeijer** [graphql-editor/diagram#75]
Either, show to which of node sides it connect, or simply draw an arrow on the center point (or endpoint, or...). 

Any way, at this moment it's sometimes impossible to see which of the nodes is the "parent" node (who has the `inputs`, and who has the `outputs` populated)

![graphsource-2](https://user-images.githubusercontent.com/1196524/53499145-10115980-3aa8-11e9-8c10-1d2881c191b2.gif)

**Comment by aexol** [comment]
I will add green hover on i/o,when selected. what do you think ?

**Comment by smeijer** [comment]
I think that will definitely be a nice addition that could fix the issue.

**Comment by smeijer** [comment]
There is another issue with the links, that could benefit from some indicator. I'm not sure how to solve it though. Perhaps a loop indicator?

The thing is, a `Node` can have its own `id` as `input` / `output`. It sounds a bit weird, but that's a good thing. My app has situations like that. 

The problem is just, the link is visually lost. Probably behind the Node? We could "bend" it, so it's a half circle. Or just 2 sharp corners?

This is how Visio would do it:

![image](https://user-images.githubusercontent.com/1196524/53501411-65e80080-3aac-11e9-8425-85a55d64e54c.png)

**Comment by aexol** [comment]
Aaah, right now you cannot connect the same node input and output. If you need it maybe I add a flag allowCircularReference on diagram

**Comment by smeijer** [comment]
In that case, you have a bug 😁 	

![image](https://user-images.githubusercontent.com/1196524/53502851-2a9b0100-3aaf-11e9-8fe9-97fb8b586042.png)

So, I don't think the `allowCircularReference` is required, as it's already possible. If one doesn't want to allow that, I guess he can filter it out with `acceptsInputs` / `acceptsOutputs`?

**Comment by smeijer** [comment]
Has this been implemented, or did you choose not to?

**Comment by aexol** [comment]
@smeijer we added arrows, but it looks I missed the hovering io part, so I am reopening.
