### ISSUE TITLE
Add option to allow overriding the NodeRenderer

### ISSUE THREAD

**Issue by smeijer** [graphql-editor/diagram#78]
It would be awesome if we could add our custom NodeRenderer. I think the most flexible way, would be to add a `getNodeRenderer` method. This would be a tiny change for this library, but open the doors for very flexible node management.

```js
import { DefaultDiagramTheme as theme } from 'graphsource/lib/Theme/DefaultDiagramTheme';
import { NodeRenderer } from 'graphsource/lib/Renderer/nodeRenderer';
import { TypeNodeRenderer, InterfaceNodeRenderer } from './myNodeRenderers';

const renderers = {
  default: NodeRenderer,
  type: TypeNodeRenderer,
  interface: InterfaceNodeRenderer,
};

const diagram = new Diagram('#id', { 
  theme: theme, 
  onConnect: () => true,
  getNodeRenderer: node => renderers[node.type] || renderers.default,
});
```

**Comment by aexol** [comment]
Maybe we should allow to override the whole renderer? 
```
class NewRenderer extends Renderer {

}
const diagram = new Diagram('#id', { 
  theme: theme, 
  renderer:NewRenderer
});
```

I am just thinking how to make it not confusing and working together with picking system. Right now you can override the theme and it should work together with picking system. 

I see you want to have different type of graphical nodes.

**Comment by smeijer** [comment]
It's hard for me to decide what's the best way of implementation. But let me explain the use case a bit.

I'm indeed in the need for "different type of graphical nodes". I need to be able to change colors, but also shapes. Based on their `node.type`.

For example, I want to show a "diamond" shape for a `node.type === 'decision'`. And the usual "rectangle" for a `node.type === 'task'`. But also, think about a `node.type === 'split'`, which would need to have one input port, and two separate output ports.

I believe I can achieve that once I can specify node renderers.

I do believe you when you would tell me that overriding the whole renderer is the easiest for this library. But then I would need to deal myself with the "edit description" and "edit name" options. And that options, I like how they work.

If I would continue this thought. I would also like it if I can override the LinkRenderer, based on the `input` and `output` node.

That way I can for example paint a `link` from a `decision` to a `task` yellow, while I paint a `link` from a `task` to a `task` green.

**Comment by smeijer** [comment]
@aexol, has this been added, or has the decision been made to not support it?
